using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Text;

namespace MapsWithLottie
{
    public class ViewModel
    {
        public ObservableCollection<Model> DataSource { get; set; }

        public ViewModel()
        {
            DataSource = new ObservableCollection<Model>();
            DataSource.Add(new Model("Afghanistan", "Asia"));
            DataSource.Add(new Model("Angola", "Africa"));
            DataSource.Add(new Model("Albania", "Europe"));
            DataSource.Add(new Model("United Arab Emirates", "Asia"));
            DataSource.Add(new Model("Argentina", "South America"));
            DataSource.Add(new Model("Armenia", "Asia"));
            DataSource.Add(new Model("Fr.S.Antarctic Lands  Seven seas", "open ocean"));
            DataSource.Add(new Model("Australia", "Australia"));
            DataSource.Add(new Model("Austria", "Europe"));
            DataSource.Add(new Model("Azerbaijan", "Asia"));
            DataSource.Add(new Model("Burundi", "Africa"));
            DataSource.Add(new Model("Russia", "Asia"));
            DataSource.Add(new Model("Belgium", "Europe"));
            DataSource.Add(new Model("Benin", "Africa"));
            DataSource.Add(new Model("Burkina Faso", "Africa"));
            DataSource.Add(new Model("Bangladesh", "Asia"));
            DataSource.Add(new Model("Bulgaria", "Europe"));
            DataSource.Add(new Model("Bahamas", "North America"));
            DataSource.Add(new Model("Bosnia and Herz.", "Europe"));
            DataSource.Add(new Model("Belarus", "Europe"));
            DataSource.Add(new Model("Belize", "North America"));
            DataSource.Add(new Model("United States of America", "North America"));
            DataSource.Add(new Model("Bolivia", "South America"));
            DataSource.Add(new Model("Brazil", "South America"));
            DataSource.Add(new Model("Brunei", "Asia"));
            DataSource.Add(new Model("Bhutan", "Asia"));
            DataSource.Add(new Model("Botswana", "Africa"));
            DataSource.Add(new Model("Central African Rep.", "Africa"));
            DataSource.Add(new Model("Canada", "North America"));
            DataSource.Add(new Model("Switzerland", "Europe"));
            DataSource.Add(new Model("Chile", "South America"));
            DataSource.Add(new Model("China", "Asia"));
            DataSource.Add(new Model("CÃƒÂ´te d'Ivoire	", "Africa"));
            DataSource.Add(new Model("Cameroon", "Africa"));
            DataSource.Add(new Model("Dem.Rep.Congo", "Africa"));
            DataSource.Add(new Model("Congo", "Africa"));
            DataSource.Add(new Model("Colombia", "South America"));
            DataSource.Add(new Model("Costa Rica", "North America"));
            DataSource.Add(new Model("Cuba", "North America"));
            DataSource.Add(new Model("N.Cyprus", "Asia"));
            DataSource.Add(new Model("Cyprus", "Asia"));
            DataSource.Add(new Model("Czech Rep.	", "Europe"));
            DataSource.Add(new Model("Germany", "Europe"));
            DataSource.Add(new Model("Djibouti", "Africa"));
            DataSource.Add(new Model("Denmark", "Europe"));
            DataSource.Add(new Model("Dominican Rep.", "North America"));
            DataSource.Add(new Model("Algeria", "Africa"));
            DataSource.Add(new Model("Ecuador", "South America"));
            DataSource.Add(new Model("Egypt", "Africa"));
            DataSource.Add(new Model("Eritrea", "Africa"));
            DataSource.Add(new Model("Spain", "Europe"));
            DataSource.Add(new Model("Estonia", "Europe"));
            DataSource.Add(new Model("Ethiopia", "Africa"));
            DataSource.Add(new Model("Finland", "Europe"));
            DataSource.Add(new Model("Fiji", "Australia"));
            DataSource.Add(new Model("Falkland Is.", "South America"));
            DataSource.Add(new Model("France", "Europe"));
            DataSource.Add(new Model("Gabon", "Africa"));
            DataSource.Add(new Model("United Kingdom", "Europe"));
            DataSource.Add(new Model("Georgia", "Asia"));
            DataSource.Add(new Model("Ghana", "Africa"));
            DataSource.Add(new Model("Guinea", "Africa"));
            DataSource.Add(new Model("Gambia", "Africa"));
            DataSource.Add(new Model("Guinea - Bissau", "Africa"));
            DataSource.Add(new Model("Eq.Guinea", "Africa"));
            DataSource.Add(new Model("Greece", "Europe"));
            DataSource.Add(new Model("Greenland", "North America"));
            DataSource.Add(new Model("Guatemala", "North America"));
            DataSource.Add(new Model("Guyana", "South America"));
            DataSource.Add(new Model("Honduras", "North America"));
            DataSource.Add(new Model("Croatia", "Europe"));
            DataSource.Add(new Model("Haiti", "North America"));
            DataSource.Add(new Model("Hungary", "Europe"));
            DataSource.Add(new Model("Indonesia", "Asia"));
            DataSource.Add(new Model("India", "Asia"));
            DataSource.Add(new Model("Ireland", "Europe"));
            DataSource.Add(new Model("Iran", "Asia"));
            DataSource.Add(new Model("Iraq", "Asia"));
            DataSource.Add(new Model("Iceland", "Europe"));
            DataSource.Add(new Model("Israel", "Asia"));
            DataSource.Add(new Model("Italy", "Europe"));
            DataSource.Add(new Model("Jamaica", "North America"));
            DataSource.Add(new Model("Jordan", "Asia"));
            DataSource.Add(new Model("Japan", "Asia"));
            DataSource.Add(new Model("Kazakhstan", "Asia"));
            DataSource.Add(new Model("Kenya", "Africa"));
            DataSource.Add(new Model("Kyrgyzstan", "Asia"));
            DataSource.Add(new Model("Cambodia", "Asia"));
            DataSource.Add(new Model("Korea", "Asia"));
            DataSource.Add(new Model("Kosovo", "Europe"));
            DataSource.Add(new Model("Kuwait", "Asia"));
            DataSource.Add(new Model("Lao PDR", "Asia"));
            DataSource.Add(new Model("Lebanon", "Asia"));
            DataSource.Add(new Model("Liberia", "Africa"));
            DataSource.Add(new Model("Libya", "Africa"));
            DataSource.Add(new Model("Sri Lanka", "Asia"));
            DataSource.Add(new Model("Lesotho", "Africa"));
            DataSource.Add(new Model("Lithuania", "Europe"));
            DataSource.Add(new Model("Luxembourg", "Europe"));
            DataSource.Add(new Model("Latvia", "Europe"));
            DataSource.Add(new Model("Morocco", "Africa"));
            DataSource.Add(new Model("Moldova", "Europe"));
            DataSource.Add(new Model("Madagascar", "Africa"));
            DataSource.Add(new Model("Mexico", "North America"));
            DataSource.Add(new Model("Macedonia", "Europe"));
            DataSource.Add(new Model("Mali", "Africa"));
            DataSource.Add(new Model("Myanmar", "Asia"));
            DataSource.Add(new Model("Montenegro", "Europe"));
            DataSource.Add(new Model("Mongolia", "Asia"));
            DataSource.Add(new Model("Mozambique", "Africa"));
            DataSource.Add(new Model("Mauritania", "Africa"));
            DataSource.Add(new Model("Malawi", "Africa"));
            DataSource.Add(new Model("Malaysia", "Asia"));
            DataSource.Add(new Model("Namibia", "Africa"));
            DataSource.Add(new Model("Caledonia", "Australia"));
            DataSource.Add(new Model("Niger", "Africa"));
            DataSource.Add(new Model("Nigeria", "Africa"));
            DataSource.Add(new Model("Nicaragua", "North America"));
            DataSource.Add(new Model("Netherlands", "Europe"));
            DataSource.Add(new Model("Norway", "Europe"));
            DataSource.Add(new Model("Nepal", "Asia"));
            DataSource.Add(new Model("Zealand", "Australia"));
            DataSource.Add(new Model("Oman", "Asia"));
            DataSource.Add(new Model("Pakistan", "Asia"));
            DataSource.Add(new Model("Panama", "North America"));
            DataSource.Add(new Model("Peru", "South America"));
            DataSource.Add(new Model("Philippines", "Asia"));
            DataSource.Add(new Model("Papua New Guinea", "Australia"));
            DataSource.Add(new Model("Poland", "Europe"));
            DataSource.Add(new Model("Puerto Rico", "North America"));
            DataSource.Add(new Model("Dem.Rep.Korea", "Asia"));
            DataSource.Add(new Model("Portugal", "Europe"));
            DataSource.Add(new Model("Paraguay", "South America"));
            DataSource.Add(new Model("Palestine", "Asia"));
            DataSource.Add(new Model("Qatar", "Asia"));
            DataSource.Add(new Model("Romania", "Europe"));
            DataSource.Add(new Model("Rwanda", "Africa"));
            DataSource.Add(new Model("W.Sahara", "Africa"));
            DataSource.Add(new Model("Saudi Arabia", "Asia"));
            DataSource.Add(new Model("Sudan", "Africa"));
            DataSource.Add(new Model("S.Sudan", "Africa"));
            DataSource.Add(new Model("Senegal", "Africa"));
            DataSource.Add(new Model("Solomon Is.", "Australia"));
            DataSource.Add(new Model("Sierra Leone", "Africa"));
            DataSource.Add(new Model("El Salvador", "North America"));
            DataSource.Add(new Model("Somaliland", "Africa"));
            DataSource.Add(new Model("Somalia", "Africa"));
            DataSource.Add(new Model("Serbia", "Europe"));
            DataSource.Add(new Model("Suriname", "South America"));
            DataSource.Add(new Model("Slovakia", "Europe"));
            DataSource.Add(new Model("Slovenia", "Europe"));
            DataSource.Add(new Model("Sweden", "Europe"));
            DataSource.Add(new Model("Swaziland", "Africa"));
            DataSource.Add(new Model("Syria", "Asia"));
            DataSource.Add(new Model("Chad", "Africa"));
            DataSource.Add(new Model("Togo", "Africa"));
            DataSource.Add(new Model("Thailand", "Asia"));
            DataSource.Add(new Model("Tajikistan", "Asia"));
            DataSource.Add(new Model("Turkmenistan", "Asia"));
            DataSource.Add(new Model("Timor - Leste", "Asia"));
            DataSource.Add(new Model("Trinidad and Tobago", "North America"));
            DataSource.Add(new Model("Tunisia", "Africa"));
            DataSource.Add(new Model("Turkey", "Asia"));
            DataSource.Add(new Model("Taiwan", "Asia"));
            DataSource.Add(new Model("Tanzania", "Africa"));
            DataSource.Add(new Model("Uganda", "Africa"));
            DataSource.Add(new Model("Ukraine", "Europe"));
            DataSource.Add(new Model("Uruguay", "South America"));
            DataSource.Add(new Model("United States", "North America"));
            DataSource.Add(new Model("Uzbekistan", "Asia"));
            DataSource.Add(new Model("Venezuela", "South America"));
            DataSource.Add(new Model("Vietnam", "Asia"));
            DataSource.Add(new Model("Vanuatu", "Australia"));
            DataSource.Add(new Model("Yemen", "Asia"));
            DataSource.Add(new Model("South", "Africa"));
            DataSource.Add(new Model("Zambia", "Africa"));
            DataSource.Add(new Model("Zimbabwe", "Africa"));
        }
    }
}
